### PR TITLE
fix: CSS inconsistencies

### LINKED ISSUE #270: Comma separated top level rules are not parsed correctly
With the following JSX:

```tsx
<div className="wrapper">
  <p className="foo">{message}</p>
  <p className="bar">{message}</p>
</div>
```

The following works as expected:

Screen Shot 2024-02-09 at 5 07 12 PM

The following does not work as expected (bug):

Screen Shot 2024-02-09 at 5 07 33 PM
Screen Shot 2024-02-09 at 5 07 26 PM

### PR DESCRIPTION
**Pull request by andy-haynes**
This PR addresses some CSS inconsistencies. Fixes #270

### CODE REVIEW

File: packages/sandbox/src/components/Preview.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export function Preview() {
   }, [accountId, debouncedFiles]);
 
   return (
-    <div className={s.wrapper}>
+    <div className={`${s.wrapper}`}>
```
Comment (calebjacob) [inline packages/sandbox/src/components/Preview.tsx:81]: @andy-haynes Curious about this syntax change. This should have been sufficient: `className={s.wrapper}`?

**Comment by calebjacob** [comment]
Thanks for getting this fixed! :)
